M48
; DRILL file {KiCad 7.0.8} date Thu Nov 23 20:50:45 2023
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-11-23T20:50:45+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.8
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0945
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.1083
%
G90
G05
T1
X10.6989Y-11.9678
T2
X10.6742Y-2.9442
X10.6742Y-5.2277
X12.6034Y-2.9442
X12.6034Y-5.2277
T0
M30
