# FROM osrf/ros:humble-desktop-full
FROM arm64v8/ros:humble-ros-base

# Install packages and dependencies
RUN apt-get update 
RUN apt-get install -y build-essential 
RUN apt-get install -y python3-colcon-common-extensions
RUN apt-get install -y ros-humble-teleop-twist-keyboard
RUN apt-get install -y ros-humble-joy
RUN apt-get install -y libserial-dev
RUN apt-get install -y libudev-dev
# RUN apt-get install -y ros-humble-gazebo-ros-pkgs
RUN apt-get install -y ros-humble-controller-manager
RUN apt-get install -y ros-humble-twist-mux
RUN apt-get install -y ros-humble-image-transport-plugins
RUN apt-get install -y ros-humble-rqt-image-view
RUN apt-get install -y ros-humble-nav2-*


# Copy entrypoint script (which creates ros user with same uid/gid as host user)
COPY entrypoint.sh /entrypoint.sh

WORKDIR /colcon_ws

# Uncomment to copy and build source_packages in colcon workspace  
# COPY ./source_packages src/source_packages 

RUN . /opt/ros/${ROS_DISTRO}/setup.sh && \
    colcon build --symlink-install --event-handlers console_direct+ --cmake-args ' -DCMAKE_BUILD_TYPE=Release'

# Set package's launch command
ENV LAUNCH_COMMAND='ros2 topic pub /talker std_msgs/msg/String "{data: Hello world}"'



# Create build and run aliases
RUN echo 'alias build="colcon build --symlink-install  --event-handlers console_direct+"' >> /etc/bash.bashrc && \
    echo 'alias run="su - ros /run.sh"' >> /etc/bash.bashrc && \
    echo "source /colcon_ws/install/setup.bash; $LAUNCH_COMMAND" >> /run.sh && chmod +x /run.sh
