name: ROS 2 Workspace Action
# You may pin to the exact commit or the version.
# uses: ros/tooling-setup-actions/setup-ros@v1

on:
  push:
    branches:
      - ezBot-ROS_ws

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ubuntu:jammy
    steps:
    -   name: ROS industrial_ci
      # You may pin to the exact commit or the version.
      # uses: 2lambda123/industrial_ci@1425bd2140a5cad7c7b831e43c443336783cc449
      uses: 2lambda123/industrial_ci@0.10.0
          
