name: Build and Test
on:
  push:
    branches:
      - ezBot-ROS_ws
jobs:
  build-and-test:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.0.0
        with:
          path: workspace

      - name: Build and test workspace
        uses: ichiro-its/ros2-ws-action@v1.0.0
        with:
          distro: rolling
