name: ROS 2 Workspace Action v2
# You may pin to the exact commit or the version.
# uses: ros/tooling-setup-actions/setup-ros@v1

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up ROS
        uses: ros/tooling-setup-actions/setup-ros@v1
        with:
          ros-distro: humble

      - name: Build workspace
        run: colcon build
