name: Build and Test
on:
  push:
    branches:
      - ezBot-ROS_ws
jobs:
  build-and-test:
    name: Build and Test
    runs-on: Ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4.0.0
        with:
          path: workspace

      - name: Setup workspace
        uses: VincidaB/ros2-ws-action/setup@v1.0.2
        with:
          distro: humble
      
      - name: Build workspace
        uses: VincidaB/ros2-ws-action/build@v1.0.2
        with:
          distro: humble
