name: Humble Source Build
# You may pin to the exact commit or the version.
# uses: ros/tooling-setup-actions/setup-ros@v1

on:
  push:
    branches:
      - ezBot-ROS_ws

jobs:
  build_docker:
    runs-on: ubuntu-latest
    container:
      image: ubuntu:jammy
    steps:
      - uses: ros-tooling/setup-ros@v0.7
        with:
          required-ros-distributions: humble
      - run: "source /opt/ros/humble/setup.bash && ros2 run --help"
      - run: "source /opt/ros/noetic/setup.bash && rosnode --help"
      - uses: ros-tooling/action-ros-ci@v0.3
        with:
          package-name: my_package
          target-ros2-distro: humble
